import './globals.css';
import type { ReactNode } from 'react';
import Header from '../components/Header';

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by Codex',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
